sensor_gpio: 25
motor_gpios: [21, 26, 20]
poll: 5 # seconds
thresholds: [0.02, 0.04, 0.08, 0.16]
mode: Auto  # Auto, Off, Low, Med, High
data_prefix: /var/log/df2000/dust_
log_prefix:  /var/log/df2000/dust.log
mock: false
mock_start: 1589722589.97081
mock_speed: 1.0
